#!/usr/bin/env bash
# Hypercolator BPF build script
#
# Wraps anchor build with the necessary environment for Solana BPF toolchain
# (platform-tools v1.41, Rust 1.75) to work with a modern Cargo registry.
#
# Key constraints (see docs/build-toolchain.md for full explanation):
#   CARGO env var - must be the rustup proxy so cargo-build-sbf uses cargo 1.88
#     for dependency resolution (proper cfg() handling for sbf-solana-solana)
#     while keeping the Solana platform-tools rustc for actual BPF compilation.
#   Cargo.lock v3 - generated by cargo +solana; required by cargo-build-sbf's
#     internal cargo 1.75 lock-file parser.
#   --no-idl - anchor-syn 0.30.1 calls the unstable proc_macro2::Span::
#     source_file() API which is not available on the Solana platform-tools
#     rustc; IDL is auto-embedded via the anchor-lang attributes instead.
#   vendor/wasm-bindgen - local patch that restricts panic_any to wasm32 so
#     wasm-bindgen compiles when cargo incorrectly includes it for sbf target.
#
# To rebuild toolchain links after container restart:
#   rustup toolchain link solana \
#     ~/.local/share/solana/install/releases/1.18.26/solana-release/bin/sdk/\
#     sbf/dependencies/platform-tools/rust
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CARGO_HOME="${CARGO_HOME:-/home/runner/workspace/.local/share/.cargo}"
PLATFORM_TOOLS_RUST="${SOLANA_INSTALL_DIR:-$HOME/.local/share/solana/install/releases/1.18.26/solana-release}/bin/sdk/sbf/dependencies/platform-tools/rust"

# Re-link the solana toolchain in case of container restart.
if [ -d "$PLATFORM_TOOLS_RUST" ]; then
  "$CARGO_HOME/bin/rustup" toolchain link solana "$PLATFORM_TOOLS_RUST" 2>/dev/null || true
fi

# Ensure the Cargo.lock is v3 (Solana cargo 1.75 format).
LOCK="$REPO_ROOT/Cargo.lock"
if [ ! -f "$LOCK" ] || head -3 "$LOCK" | grep -q "version = 4"; then
  echo "Re-generating Cargo.lock as v3..."
  "$CARGO_HOME/bin/cargo" +solana generate-lockfile \
    --manifest-path "$REPO_ROOT/Cargo.toml"
fi

cd "$REPO_ROOT"
echo "=== anchor build --no-idl ==="
CARGO="$CARGO_HOME/bin/cargo" anchor build --no-idl "$@"

echo ""
echo "Build OK.  Output: $REPO_ROOT/target/deploy/hypercolator.so"
